version: '{build}'
image: Visual Studio 2019

init:
  - ps: |
      Write-Host "Hello Tag: $Env:APPVEYOR_REPO_TAG_NAME"
      If($Env:APPVEYOR_REPO_TAG -eq "true")
      {
        Set-AppveyorBuildVariable 'APPVEYOR_BUILD_VERSION' '$Env:APPVEYOR_REPO_TAG_NAME'
      } 
      else 
      {
        $releases = "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases"
        $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
        $spl = $tag.Split("-")[0]
        Set-AppveyorBuildVariable 'APPVEYOR_BUILD_VERSION' '$spl.$Env:APPVEYOR_BUILD_VERSION-wip'
      }
      Write-Host "Hello. Build version for SpeckleUiBase is: $Env:APPVEYOR_BUILD_VERSION"
      Write-Host "Test."

before_build:
- cmd: >-
    nuget restore
# version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  include_nuget_references: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  project: SpeckleUiBase\SpeckleUiBase.csproj
  verbosity: minimal

deploy:
  - provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: n4EiHDLVSLjOzqT7OOOg3US3PWs6fNsOaGpyT/EFBKrTKl/1wMmmKt73MNuTngD+
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    on:
      appveyor_repo_tag: true

platform:
  - x64

configuration:
  - Release
